import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'config/api_config.dart';

String orderItemNameOf(dynamic item) {
  if (item is Map) {
    return (item['item_name'] ?? item['name'] ?? 'Unknown Medicine').toString();
  }
  return 'Unknown Medicine';
}

int orderItemQtyOf(dynamic item) {
  if (item is! Map) return 0;
  final value = item['qty'] ?? item['suggested_qty'] ?? item['quantity'] ?? 0;
  if (value is int) return value;
  return int.tryParse(value.toString()) ?? 0;
}

class OrderHistoryPage extends StatefulWidget {
  final String clinicId;

  const OrderHistoryPage({super.key, required this.clinicId});

  @override
  _OrderHistoryPageState createState() => _OrderHistoryPageState();
}

class _OrderHistoryPageState extends State<OrderHistoryPage> {
  List orders = [];
  bool isLoading = true;

  final String baseUrl = ApiConfig.baseUrl;

  @override
  void initState() {
    super.initState();
    fetchOrders();
  }

  Future<void> fetchOrders() async {
    final response = await http.get(
      Uri.parse('$baseUrl/orders?clinic_id=${widget.clinicId}'),
    );

    if (response.statusCode == 200) {
      final data = json.decode(response.body);
      final List<Map<String, dynamic>> fetchedOrders =
          (data['orders'] as List<dynamic>)
              .map((order) => Map<String, dynamic>.from(order))
              .toList();

      fetchedOrders.sort((a, b) {
        final dateA =
            DateTime.tryParse(a['created_at'].toString()) ??
            DateTime.fromMillisecondsSinceEpoch(0);
        final dateB =
            DateTime.tryParse(b['created_at'].toString()) ??
            DateTime.fromMillisecondsSinceEpoch(0);
        return dateB.compareTo(dateA);
      });

      setState(() {
        orders = fetchedOrders;
        isLoading = false;
      });
    }
  }

  Future<void> updateOrderStatus(String orderId, String status) async {
    final url = Uri.parse('$baseUrl/update_order_status');

    final response = await http.post(
      url,
      headers: {"Content-Type": "application/json"},
      body: json.encode({"order_id": orderId, "status": status}),
    );

    if (response.statusCode == 200) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Status updated to $status ✅")));

      await fetchOrders();

      if (!mounted) return;

      Navigator.pop(context, true);
    } else {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text("Failed ❌")));
    }
  }

  Future<Uint8List> buildHistoricalPdf(Map<String, dynamic> order) async {
    final pdf = pw.Document();
    final orderDate = (order['created_at'] ?? '').toString().length >= 10
        ? (order['created_at'] ?? '').toString().substring(0, 10)
        : (order['created_at'] ?? '').toString();
    final items = order['items'] as List<dynamic>? ?? [];
    final status = order['status'] as String? ?? 'N/A';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Container(
          alignment: pw.Alignment.center,
          padding: const pw.EdgeInsets.only(bottom: 20),
          child: pw.Column(
            children: [
              pw.Text(
                "AI-Assisted Pharmacy Inventory System",
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                "Historical Order Document",
                style: pw.TextStyle(
                  fontSize: 13,
                  color: const PdfColor.fromInt(0xFF666666),
                ),
              ),
            ],
          ),
        ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          padding: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            "Generated by AI-Assisted Pharmacy Inventory System",
            style: pw.TextStyle(
              fontSize: 9,
              color: const PdfColor.fromInt(0xFF999999),
            ),
          ),
        ),
        build: (context) => [
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: const PdfColor.fromInt(0xFFCCCCCC)),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text("Clinic ID: ${widget.clinicId}",
                        style: const pw.TextStyle(fontSize: 11)),
                    pw.SizedBox(height: 4),
                    pw.Text("Order Date: $orderDate",
                        style: const pw.TextStyle(fontSize: 11)),
                    pw.SizedBox(height: 4),
                    pw.Text("Status: $status",
                        style: const pw.TextStyle(fontSize: 11)),
                  ],
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            "Medicine List",
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Table(
            border: pw.TableBorder.all(
              color: const PdfColor.fromInt(0xFFCCCCCC),
              width: 0.5,
            ),
            columnWidths: const {
              0: pw.FlexColumnWidth(1),
              1: pw.FlexColumnWidth(6),
              2: pw.FlexColumnWidth(2),
            },
            children: [
              pw.TableRow(
                decoration: const pw.BoxDecoration(
                  color: PdfColor.fromInt(0xFF333333),
                ),
                children: [
                  pw.Container(
                    padding: const pw.EdgeInsets.all(8),
                    child: pw.Text("No",
                        style: pw.TextStyle(
                            fontSize: 10,
                            fontWeight: pw.FontWeight.bold,
                            color: const PdfColor.fromInt(0xFFFFFFFF))),
                  ),
                  pw.Container(
                    padding: const pw.EdgeInsets.all(8),
                    child: pw.Text("Medicine",
                        style: pw.TextStyle(
                            fontSize: 10,
                            fontWeight: pw.FontWeight.bold,
                            color: const PdfColor.fromInt(0xFFFFFFFF))),
                  ),
                  pw.Container(
                    padding: const pw.EdgeInsets.all(8),
                    child: pw.Text("Quantity",
                        style: pw.TextStyle(
                            fontSize: 10,
                            fontWeight: pw.FontWeight.bold,
                            color: const PdfColor.fromInt(0xFFFFFFFF)),
                        textAlign: pw.TextAlign.right),
                  ),
                ],
              ),
              ...items.asMap().entries.map(
                    (entry) => pw.TableRow(
                      children: [
                        pw.Container(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text("${entry.key + 1}",
                              style: const pw.TextStyle(fontSize: 10)),
                        ),
                        pw.Container(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text(orderItemNameOf(entry.value),
                              style: const pw.TextStyle(fontSize: 10)),
                        ),
                        pw.Container(
                          padding: const pw.EdgeInsets.all(8),
                          child: pw.Text(
                              "${orderItemQtyOf(entry.value)}",
                              style: const pw.TextStyle(fontSize: 10),
                              textAlign: pw.TextAlign.right),
                        ),
                      ],
                    ),
                  ),
            ],
          ),
        ],
      ),
    );

    return pdf.save();
  }

  Future<void> downloadHistoricalPdf(Map<String, dynamic> order) async {
    final pdfBytes = await buildHistoricalPdf(order);
    final dateStr = (order['created_at'] ?? '').toString().length >= 10
        ? (order['created_at'] ?? '').toString().substring(0, 10).replaceAll('-', '_')
        : DateTime.now().toIso8601String().split('T').first;

    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(title: const Text("Order PDF Preview")),
          body: PdfPreview(
            build: (format) => pdfBytes,
            pdfFileName:
                "order_${widget.clinicId}_$dateStr.pdf",
            canChangePageFormat: false,
            canChangeOrientation: false,
            canDebug: false,
          ),
        ),
      ),
    );
  }

  Color getStatusColor(String status) {
    switch (status) {
      case "DRAFT":
        return Colors.orange;
      case "SUBMITTED":
        return Colors.blue;
      case "RECEIVED":
        return Colors.green;
      default:
        return Colors.grey;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Order History")),
      body: isLoading
          ? const Center(child: CircularProgressIndicator())
          : orders.isEmpty
          ? const Center(child: Text("No orders yet"))
          : ListView.builder(
              itemCount: orders.length,
              itemBuilder: (context, index) {
                final order = orders[index];
                final items = order['items'] as List<dynamic>? ?? [];
                final itemCount = items.length;

                return Card(
                  margin: const EdgeInsets.all(10),
                  child: Padding(
                    padding: const EdgeInsets.all(12),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            Container(
                              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                              decoration: BoxDecoration(
                                color: getStatusColor(order['status']).withValues(alpha: 0.15),
                                borderRadius: BorderRadius.circular(12),
                              ),
                              child: Text(
                                order['status'] ?? 'UNKNOWN',
                                style: TextStyle(
                                  color: getStatusColor(order['status']),
                                  fontWeight: FontWeight.bold,
                                  fontSize: 12,
                                ),
                              ),
                            ),
                            const Spacer(),
                            Text(
                              "${itemCount} item${itemCount != 1 ? 's' : ''}",
                              style: TextStyle(fontSize: 12, color: Colors.grey[600]),
                            ),
                          ],
                        ),
                        const SizedBox(height: 6),
                        Text(
                          "Date: ${order['created_at']}",
                          style: TextStyle(fontSize: 13, color: Colors.grey[600]),
                        ),
                        const SizedBox(height: 10),
                        ...items.take(3).map<Widget>((item) {
                          return Padding(
                            padding: const EdgeInsets.only(bottom: 2),
                            child: Text(
                              "• ${orderItemNameOf(item)} — ${orderItemQtyOf(item)}",
                              style: const TextStyle(fontSize: 13),
                            ),
                          );
                        }).toList(),
                        if (itemCount > 3)
                          Text(
                            "... and ${itemCount - 3} more items",
                            style: TextStyle(fontSize: 12, fontStyle: FontStyle.italic, color: Colors.grey[500]),
                          ),
                        const SizedBox(height: 10),
                        Row(
                          children: [
                            if (order['status'] == "DRAFT")
                              Expanded(
                                child: ElevatedButton(
                                  onPressed: () =>
                                      updateOrderStatus(order['id'], "SUBMITTED"),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: Colors.orange,
                                    foregroundColor: Colors.white,
                                    padding: const EdgeInsets.symmetric(vertical: 10),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                  ),
                                  child: const Text("Submit to PKD"),
                                ),
                              ),
                            if (order['status'] == "DRAFT")
                              const SizedBox(width: 8),
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: () => downloadHistoricalPdf(order),
                                icon: const Icon(Icons.picture_as_pdf_outlined, size: 16),
                                label: const Text("Download PDF"),
                                style: OutlinedButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(vertical: 10),
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                );
              },
            ),
    );
  }
}